### ISSUE TITLE
Construir dataset 2D de cavidades

### ISSUE THREAD

**Issue by gustavercosa** [jvsguerra/pyKVFinder#3]
Construção de um conjunto de imagens 2D representativas dos tipos de cavidades proteicas, que são:
- Bolsão enclausurado (_void_);
- Invaginação (_invagination_);
- Tunel (_tunnel_);
- Canal (_channel_);
- Fenda superficial (_cleft_ ou _groove_);

**Comment by jvsguerra** [comment]
@gustavercosa Crie uma pasta no caminho `pyKVFinder/examples/morphology` (ou qualquer outro nome que achar adequado) em seu fork do [pyKVFinder](https://github.com/gustavercosa/pyKVFinder). Dentro dela, coloque em um pasta `2D`, as imagens com os nomes do tipo de cavidade que elas representam.

Passo-a-passo:
```bash
# Dentro da pasta do seu fork do pyKVFinder
cd examples
mkdir morphology
cd morphology
mdkir 2D
cp /caminho/para/<imagens>.png /caminho/para/examples/morphology/2D/
```

Se o conjunto já for final, faça um Pull Request para o meu [fork](https://github.com/jvsguerra/pyKVFinder) em um novo branch (p. ex. `ip-2023.1`).
